#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.7
# In conjunction with Tcl version 8.6
#    Apr 24, 2016 01:35:43 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import confirmationreserve_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Confirm_screen (root)
    confirmationreserve_support.init(root, top)
    root.mainloop()

w = None
def create_Confirm_screen(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Confirm_screen (w)
    confirmationreserve_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Confirm_screen():
    global w
    w.destroy()
    w = None


class Confirm_screen:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {DejaVu Sans} -size 20 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"

        top.geometry("600x450+315+169")
        top.title("Confirm screen")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.33, rely=0.09, height=33, width=165)
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#ffb800")
        self.Label1.configure(text='''Confirmation''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.18, rely=0.29, height=18, width=87)
        self.Label2.configure(text='''ReservationID''')

        self.Text1 = Text(top)
        self.Text1.place(relx=0.33, rely=0.27, relheight=0.09, relwidth=0.23)
        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(width=136)
        self.Text1.configure(wrap=WORD)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.18, rely=0.44, height=18, width=182)
        self.Label3.configure(text='''Thank you for your Purchase!''')

        self.Label4 = Label(top)
        self.Label4.place(relx=0.18, rely=0.51, height=18, width=220)
        self.Label4.configure(text='''Save ReservationID for your records''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.3, rely=0.67, height=26, width=209)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''Return to Functionality screen''')






if __name__ == '__main__':
    vp_start_gui()



