#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.7
# In conjunction with Tcl version 8.6
#    Apr 22, 2016 11:50:12 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import prototype2_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Toplevel (root)
    prototype2_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Toplevel (w)
    prototype2_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel():
    global w
    w.destroy()
    w = None


class Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {DejaVu Sans} -size 20 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"

        top.geometry("640x451+334+213")
        top.title("Toplevel")
        top.configure(highlightcolor="black")



        self.loginScreen = Frame(top)
        self.loginScreen.place(relx=0.02, rely=0.0, relheight=0.94
                , relwidth=0.96)
        self.loginScreen.configure(relief=GROOVE)
        self.loginScreen.configure(borderwidth="2")
        self.loginScreen.configure(relief=GROOVE)
        self.loginScreen.configure(width=615)

        self.loginbutton = Button(self.loginScreen)
        self.loginbutton.place(relx=0.36, rely=0.54, height=26, width=59)
        self.loginbutton.configure(activebackground="#d9d9d9")
        self.loginbutton.configure(text='''Login''')

        self.regbutton = Button(self.loginScreen)
        self.regbutton.place(relx=0.54, rely=0.54, height=26, width=75)
        self.regbutton.configure(activebackground="#d9d9d9")
        self.regbutton.configure(text='''Register''')

        self.Entryusr = Entry(self.loginScreen)
        self.Entryusr.place(relx=0.36, rely=0.28, relheight=0.06, relwidth=0.33)
        self.Entryusr.configure(background="white")
        self.Entryusr.configure(font="TkFixedFont")
        self.Entryusr.configure(selectbackground="#c4c4c4")
        self.Entryusr.configure(width=186)

        self.Entrypwd = Entry(self.loginScreen)
        self.Entrypwd.place(relx=0.36, rely=0.4, relheight=0.06, relwidth=0.33)
        self.Entrypwd.configure(background="white")
        self.Entrypwd.configure(font="TkFixedFont")
        self.Entrypwd.configure(selectbackground="#c4c4c4")

        self.Label1 = Label(self.loginScreen)
        self.Label1.place(relx=0.24, rely=0.28, height=18, width=65)
        self.Label1.configure(text='''Username''')

        self.Label2 = Label(self.loginScreen)
        self.Label2.place(relx=0.24, rely=0.41, height=18, width=60)
        self.Label2.configure(text='''Password''')

        self.customerFuncs = Frame(top)
        self.customerFuncs.place(relx=0.05, rely=0.02, relheight=0.88
                , relwidth=0.88)
        self.customerFuncs.configure(relief=GROOVE)
        self.customerFuncs.configure(borderwidth="2")
        self.customerFuncs.configure(relief=GROOVE)
        self.customerFuncs.configure(width=565)

        self.Button1 = Button(self.customerFuncs)
        self.Button1.place(relx=0.32, rely=0.13, height=26, width=152)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''View train Schedules''')

        self.Button2 = Button(self.customerFuncs)
        self.Button2.place(relx=0.32, rely=0.23, height=26, width=172)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(text='''Make a New Reservation''')

        self.Button5 = Button(self.customerFuncs)
        self.Button5.place(relx=0.32, rely=0.33, height=26, width=155)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(text='''Update a Reservation''')

        self.Button6 = Button(self.customerFuncs)
        self.Button6.place(relx=0.32, rely=0.43, height=26, width=152)
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(text='''Cancel A Reservation''')

        self.Button7 = Button(self.customerFuncs)
        self.Button7.place(relx=0.32, rely=0.53, height=26, width=98)
        self.Button7.configure(activebackground="#d9d9d9")
        self.Button7.configure(text='''Give Review''')

        self.Button8 = Button(self.customerFuncs)
        self.Button8.place(relx=0.32, rely=0.63, height=26, width=130)
        self.Button8.configure(activebackground="#d9d9d9")
        self.Button8.configure(text='''Add Student Info''')

        self.logoutbutton = Button(self.customerFuncs)
        self.logoutbutton.place(relx=0.67, rely=0.81, height=26, width=68)
        self.logoutbutton.configure(activebackground="#d9d9d9")
        self.logoutbutton.configure(text='''Logout''')

        self.menubar = Menu(top,bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.menubar.add_command(
                activebackground="#d9d9d9",
                background="#d9d9d9",
                command=prototype2_support.TODO,
                foreground="#000000",
                label="NewCommand")


        self.Frame3 = Frame(top)
        self.Frame3.place(relx=0.05, rely=0.07, relheight=0.76, relwidth=0.82)
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(width=525)

        self.Label3 = Label(self.Frame3)
        self.Label3.place(relx=0.34, rely=0.12, height=58, width=172)
        self.Label3.configure(font=font10)
        self.Label3.configure(text='''Add School''')
        self.Label3.configure(width=172)

        self.Entryschool = Entry(self.Frame3)
        self.Entryschool.place(relx=0.4, rely=0.35, relheight=0.06
                , relwidth=0.28)
        self.Entryschool.configure(background="white")
        self.Entryschool.configure(font="TkFixedFont")

        self.Label4 = Label(self.Frame3)
        self.Label4.place(relx=0.13, rely=0.35, height=18, width=133)
        self.Label4.configure(text='''School Email Address''')

        self.backshbutton = Button(self.Frame3)
        self.backshbutton.place(relx=0.27, rely=0.64, height=26, width=55)
        self.backshbutton.configure(activebackground="#d9d9d9")
        self.backshbutton.configure(text='''Back''')

        self.submitstubutton = Button(self.Frame3)
        self.submitstubutton.place(relx=0.53, rely=0.64, height=26, width=70)
        self.submitstubutton.configure(activebackground="#d9d9d9")
        self.submitstubutton.configure(text='''Submit''')






if __name__ == '__main__':
    vp_start_gui()

