#############################################################################
# Generated by PAGE version 4.7
# in conjunction with Tcl version 8.6
#    Apr 24, 2016 12:56:12 AM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans} -size 20 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font14
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra38
    set site_4_0 $site_3_0.scr47
    set site_4_0 $site_3_0.scr48
    set site_4_0 $site_3_0.fra59
    set site_3_0 $base.fra73
    set site_3_0 $base.fra81
    set site_4_0 $site_3_0.scr84

    #Updating ttreeview attributes
    .top36.fra81.scr84.01 configure\
        -columns  "Col1 Col2 Col3 Col4 Col5 Col6 Col7"\
        -height  4

    #heading options.
    .top36.fra81.scr84.01 heading Col1 \
             -text "Time" \
             -anchor center
    #heading options.
    .top36.fra81.scr84.01 heading Col2 \
             -text "Departs" \
             -anchor center
    #heading options.
    .top36.fra81.scr84.01 heading Col3 \
             -text "Arrival" \
             -anchor center
    #heading options.
    .top36.fra81.scr84.01 heading Col4 \
             -text "Class" \
             -anchor center
    #heading options.
    .top36.fra81.scr84.01 heading Col5 \
             -text "Price" \
             -anchor center
    #heading options.
    .top36.fra81.scr84.01 heading Col6 \
             -text "# Bags" \
             -anchor center
    #heading options.
    .top36.fra81.scr84.01 heading Col7 \
             -text "Name" \
             -anchor center
    #heading options.
    .top36.fra81.scr84.01 heading #0 \
             -text "Train" \
             -anchor center
    #column options.
    .top36.fra81.scr84.01 column Col1 \
             -width 105 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    #column options.
    .top36.fra81.scr84.01 column Col2 \
             -width 106 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    #column options.
    .top36.fra81.scr84.01 column Col3 \
             -width 106 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    #column options.
    .top36.fra81.scr84.01 column Col4 \
             -width 46 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    #column options.
    .top36.fra81.scr84.01 column Col5 \
             -width 50 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    #column options.
    .top36.fra81.scr84.01 column Col6 \
             -width 48 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    #column options.
    .top36.fra81.scr84.01 column Col7 \
             -width 61 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    #column options.
    .top36.fra81.scr84.01 column #0 \
             -width 105 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m36" -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 704x460+324+265
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1165 768
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra38 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 395 \
        -highlightcolor black -width 555 
    vTcl:DefineAlias "$top.fra38" "searchtrain" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra38
    label $site_3_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffa300} -highlightcolor black -text {Search Train} 
    vTcl:DefineAlias "$site_3_0.lab39" "Label1-3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Deaparts from} 
    vTcl:DefineAlias "$site_3_0.lab40" "Label2-3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab38 \
        -background {#d9d9d9} -foreground {#000000} -text {Arrives At} 
    vTcl:DefineAlias "$site_3_0.lab38" "Label3-3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab41 \
        -background {#d9d9d9} -foreground {#000000} \
        -text {Departure Date (DD/MM/YYYY)} 
    vTcl:DefineAlias "$site_3_0.lab41" "Label4-3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent43 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent43" "Entrydate" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_3_0.scr47 \
        -background {#d9d9d9} -height 59 -highlightcolor black -width 76 
    vTcl:DefineAlias "$site_3_0.scr47" "Scrolledlistbox1" vTcl:WidgetProc "Toplevel1" 1

    $site_3_0.scr47.01 configure -background white \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_3_0.scr48 \
        -background {#d9d9d9} -height 69 -highlightcolor black -width 76 
    vTcl:DefineAlias "$site_3_0.scr48" "Scrolledlistbox2" vTcl:WidgetProc "Toplevel1" 1

    $site_3_0.scr48.01 configure -background white \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    button $site_3_0.but49 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text {Find Trains} 
    vTcl:DefineAlias "$site_3_0.but49" "Buttonsearchtrain" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra59 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 375 \
        -width 545 
    vTcl:DefineAlias "$site_3_0.fra59" "searchdeparture" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra59
    label $site_4_0.cpd60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffa300} -highlightcolor black -text {Search Departure} 
    vTcl:DefineAlias "$site_4_0.cpd60" "Label4-4" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab62 \
        -background {#d9d9d9} -foreground {#000000} -text {Select Train} 
    vTcl:DefineAlias "$site_4_0.lab62" "Label5-4" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_0.tCo63 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo63" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_0.tLa64 \
        -background {#d9d9d9} -foreground {#000000} -relief flat -text {} \
        -textvariable deptime 
    vTcl:DefineAlias "$site_4_0.tLa64" "departue time" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_0.tLa65 \
        -background {#d9d9d9} -foreground {#000000} -relief flat -text time 
    vTcl:DefineAlias "$site_4_0.tLa65" "tlabel" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_0.tCo67 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo67" "TCombobox2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab68 \
        -background {#d9d9d9} -foreground {#000000} -text {Select class} 
    vTcl:DefineAlias "$site_4_0.lab68" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab69 \
        -background {#d9d9d9} -foreground {#000000} -text Cost 
    vTcl:DefineAlias "$site_4_0.lab69" "Label7" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_0.tLa70 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -textvariable depticketcost 
    vTcl:DefineAlias "$site_4_0.tLa70" "ticketcost" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but71 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text back 
    vTcl:DefineAlias "$site_4_0.but71" "Buttontosearch" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but72 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text Next 
    vTcl:DefineAlias "$site_4_0.but72" "Buttontoextras" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.cpd60 \
        -in $site_4_0 -x 170 -y 20 -width 251 -height 53 -anchor nw \
        -bordermode inside 
    place $site_4_0.lab62 \
        -in $site_4_0 -x 50 -y 80 -anchor nw -bordermode ignore 
    place $site_4_0.tCo63 \
        -in $site_4_0 -x 50 -y 100 -anchor nw -bordermode ignore 
    place $site_4_0.tLa64 \
        -in $site_4_0 -x 60 -y 140 -width 82 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa65 \
        -in $site_4_0 -x 60 -y 130 -anchor nw -bordermode ignore 
    place $site_4_0.tCo67 \
        -in $site_4_0 -x 300 -y 100 -anchor nw -bordermode ignore 
    place $site_4_0.lab68 \
        -in $site_4_0 -x 300 -y 80 -anchor nw -bordermode ignore 
    place $site_4_0.lab69 \
        -in $site_4_0 -x 300 -y 130 -anchor nw -bordermode ignore 
    place $site_4_0.tLa70 \
        -in $site_4_0 -x 300 -y 150 -width 87 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but71 \
        -in $site_4_0 -x 100 -y 220 -anchor nw -bordermode ignore 
    place $site_4_0.but72 \
        -in $site_4_0 -x 330 -y 220 -anchor nw -bordermode ignore 
    place $site_3_0.lab39 \
        -in $site_3_0 -x 190 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab40 \
        -in $site_3_0 -x 120 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.lab38 \
        -in $site_3_0 -x 130 -y 170 -anchor nw -bordermode ignore 
    place $site_3_0.lab41 \
        -in $site_3_0 -x 40 -y 240 -anchor nw -bordermode ignore 
    place $site_3_0.ent43 \
        -in $site_3_0 -x 240 -y 240 -anchor nw -bordermode ignore 
    place $site_3_0.scr47 \
        -in $site_3_0 -x 230 -y 90 -width 76 -height 59 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr48 \
        -in $site_3_0 -x 230 -y 160 -width 76 -height 69 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 240 -y 280 -anchor nw -bordermode ignore 
    place $site_3_0.fra59 \
        -in $site_3_0 -x 0 -y 0 -width 545 -height 375 -anchor nw \
        -bordermode ignore 
    menu $top.m36 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    frame $top.fra73 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 335 \
        -width 555 
    vTcl:DefineAlias "$top.fra73" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra73
    label $site_3_0.cpd74 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffa300} -highlightcolor black \
        -text {Travel Extras & Passenger Info} 
    vTcl:DefineAlias "$site_3_0.cpd74" "Label8-3" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo75 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo75" "TCombobox3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab76 \
        -background {#d9d9d9} -foreground {#000000} -text {Number of Baggage} 
    vTcl:DefineAlias "$site_3_0.lab76" "Label9" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent77 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent77" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but78 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text {Passenger name} 
    vTcl:DefineAlias "$site_3_0.but78" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but79 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text Back 
    vTcl:DefineAlias "$site_3_0.but79" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but80 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text Next 
    vTcl:DefineAlias "$site_3_0.but80" "Button6" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.cpd74 \
        -in $site_3_0 -x 62 -y 2 -width 421 -height 63 -anchor nw \
        -bordermode inside 
    place $site_3_0.tCo75 \
        -in $site_3_0 -x 250 -y 110 -width 117 -height 18 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 90 -y 110 -anchor nw -bordermode ignore 
    place $site_3_0.ent77 \
        -in $site_3_0 -x 260 -y 150 -anchor nw -bordermode ignore 
    place $site_3_0.but78 \
        -in $site_3_0 -x 100 -y 150 -anchor nw -bordermode ignore 
    place $site_3_0.but79 \
        -in $site_3_0 -x 90 -y 230 -anchor nw -bordermode ignore 
    place $site_3_0.but80 \
        -in $site_3_0 -x 330 -y 230 -anchor nw -bordermode ignore 
    frame $top.fra81 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 345 \
        -width 655 
    vTcl:DefineAlias "$top.fra81" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra81
    label $site_3_0.cpd82 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffa300} -highlightcolor black -text {Make Reservation} 
    vTcl:DefineAlias "$site_3_0.cpd82" "Label10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab83 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font14,object) \
        -foreground {#000000} -text {Currently Selected} 
    vTcl:DefineAlias "$site_3_0.lab83" "Label11" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font TkDefaultFont
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_3_0.scr84 \
        -background {#d9d9d9} -height 108 -highlightcolor black -width 555 
    vTcl:DefineAlias "$site_3_0.scr84" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but85 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text {Remove Selected} 
    vTcl:DefineAlias "$site_3_0.but85" "Button7" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but86 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text Back 
    vTcl:DefineAlias "$site_3_0.but86" "Button8" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but87 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text Submit 
    vTcl:DefineAlias "$site_3_0.but87" "Button9" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but88 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text Continue 
    vTcl:DefineAlias "$site_3_0.but88" "Button10" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.cpd82 \
        -in $site_3_0 -x 70 -y 20 -width 421 -height 63 -anchor nw \
        -bordermode inside 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 60 -y 70 -anchor nw -bordermode ignore 
    place $site_3_0.scr84 \
        -in $site_3_0 -x 10 -y 90 -width 641 -height 108 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but85 \
        -in $site_3_0 -x 130 -y 210 -anchor nw -bordermode ignore 
    place $site_3_0.but86 \
        -in $site_3_0 -x 70 -y 310 -anchor nw -bordermode ignore 
    place $site_3_0.but87 \
        -in $site_3_0 -x 180 -y 310 -anchor nw -bordermode ignore 
    place $site_3_0.but88 \
        -in $site_3_0 -x 130 -y 250 -width 117 -height 26 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra38 \
        -in $top -x 20 -y 30 -width 555 -height 395 -anchor nw \
        -bordermode ignore 
    place $top.fra73 \
        -in $top -x 20 -y 50 -width 555 -height 335 -anchor nw \
        -bordermode ignore 
    place $top.fra81 \
        -in $top -x 10 -y 20 -width 655 -height 345 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

