#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.7
# In conjunction with Tcl version 8.6
#    Apr 24, 2016 03:05:41 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import managerview_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Mananger_Functions (root)
    managerview_support.init(root, top)
    root.mainloop()

w = None
def create_Mananger_Functions(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Mananger_Functions (w)
    managerview_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Mananger_Functions():
    global w
    w.destroy()
    w = None


class Mananger_Functions:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {DejaVu Sans} -size 20 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"

        top.geometry("600x450+237+162")
        top.title("Mananger Functions")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.18, rely=0.09, height=33, width=283)
        self.Label1.configure(font=font10)
        self.Label1.configure(text='''Manager Functionality''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.3, rely=0.22, height=26, width=151)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''View revenue Report''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.3, rely=0.33, height=26, width=186)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(text='''View Popular Route Report''')

        self.Button3 = Button(top)
        self.Button3.place(relx=0.3, rely=0.44, height=26, width=68)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(text='''Logout''')






if __name__ == '__main__':
    vp_start_gui()



