#############################################################################
# Generated by PAGE version 4.7
# in conjunction with Tcl version 8.6
#    Apr 24, 2016 01:16:41 AM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans} -size 20 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 12 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 600x450+301+142
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1165 768
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Payment Info"
    vTcl:DefineAlias "$top" "Paymentinfo" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab37 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffbe00} -text {Payment Info} 
    vTcl:DefineAlias "$top.lab37" "Label1" vTcl:WidgetProc "Paymentinfo" 1
    label $top.lab38 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -text {Add Card} 
    vTcl:DefineAlias "$top.lab38" "Label2" vTcl:WidgetProc "Paymentinfo" 1
    label $top.lab39 \
        -background {#d9d9d9} -foreground {#000000} -text {Name on Card} 
    vTcl:DefineAlias "$top.lab39" "Label3" vTcl:WidgetProc "Paymentinfo" 1
    entry $top.ent40 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent40" "Entry1" vTcl:WidgetProc "Paymentinfo" 1
    label $top.lab41 \
        -background {#d9d9d9} -foreground {#000000} -text {Card Number} 
    vTcl:DefineAlias "$top.lab41" "Label4" vTcl:WidgetProc "Paymentinfo" 1
    entry $top.ent42 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent42" "Entry2" vTcl:WidgetProc "Paymentinfo" 1
    entry $top.ent43 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent43" "Entry3" vTcl:WidgetProc "Paymentinfo" 1
    label $top.lab45 \
        -background {#d9d9d9} -foreground {#000000} -text CVV 
    vTcl:DefineAlias "$top.lab45" "Label5" vTcl:WidgetProc "Paymentinfo" 1
    entry $top.ent46 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent46" "Entry4" vTcl:WidgetProc "Paymentinfo" 1
    label $top.lab48 \
        -background {#d9d9d9} -foreground {#000000} -text {Expiration Date} 
    vTcl:DefineAlias "$top.lab48" "Label6" vTcl:WidgetProc "Paymentinfo" 1
    button $top.but49 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text Submit 
    vTcl:DefineAlias "$top.but49" "Button1" vTcl:WidgetProc "Paymentinfo" 1
    label $top.cpd50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -text {Delete Card} 
    vTcl:DefineAlias "$top.cpd50" "Label7" vTcl:WidgetProc "Paymentinfo" 1
    ttk::combobox $top.tCo51 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo51" "TCombobox1" vTcl:WidgetProc "Paymentinfo" 1
    label $top.lab52 \
        -background {#d9d9d9} -foreground {#000000} \
        -text {select card number} 
    vTcl:DefineAlias "$top.lab52" "Label8" vTcl:WidgetProc "Paymentinfo" 1
    button $top.cpd53 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Delete 
    vTcl:DefineAlias "$top.cpd53" "Button2" vTcl:WidgetProc "Paymentinfo" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab37 \
        -in $top -x 200 -y 40 -anchor nw -bordermode ignore 
    place $top.lab38 \
        -in $top -x 90 -y 90 -anchor nw -bordermode ignore 
    place $top.lab39 \
        -in $top -x 70 -y 140 -anchor nw -bordermode ignore 
    place $top.ent40 \
        -in $top -x 180 -y 140 -anchor nw -bordermode ignore 
    place $top.lab41 \
        -in $top -x 70 -y 170 -anchor nw -bordermode ignore 
    place $top.ent42 \
        -in $top -x 180 -y 170 -anchor nw -bordermode ignore 
    place $top.ent43 \
        -in $top -x 180 -y 200 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 80 -y 200 -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 180 -y 240 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 70 -y 240 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 80 -y 280 -anchor nw -bordermode ignore 
    place $top.cpd50 \
        -in $top -x 360 -y 90 -width 102 -height 22 -anchor nw \
        -bordermode inside 
    place $top.tCo51 \
        -in $top -x 380 -y 160 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 380 -y 130 -anchor nw -bordermode ignore 
    place $top.cpd53 \
        -in $top -x 390 -y 200 -width 70 -height 26 -anchor nw \
        -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

