#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.7
# In conjunction with Tcl version 8.6
#    Apr 24, 2016 02:22:59 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import updatereserv_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Update_reservation (root)
    updatereserv_support.init(root, top)
    root.mainloop()

w = None
def create_Update_reservation(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Update_reservation (w)
    updatereserv_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Update_reservation():
    global w
    w.destroy()
    w = None


class Update_reservation:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {DejaVu Sans} -size 20 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("677x450+201+155")
        top.title("Update reservation")



        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.31, rely=0.31, relheight=0.04, relwidth=0.22)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")

        self.Label1 = Label(top)
        self.Label1.place(relx=0.15, rely=0.31, height=18, width=87)
        self.Label1.configure(text='''ReservationID''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.25, rely=0.09, height=33, width=250)
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#f69e00")
        self.Label2.configure(text='''Update Reservation''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.55, rely=0.31, height=26, width=68)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''Search''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.21, rely=0.44, height=26, width=57)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(text='''Close''')

        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.01, rely=0.2, relheight=0.77, relwidth=0.95)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(width=645)

        self.style.configure('Treeview.Heading',  font="TkDefaultFont")
        self.Scrolledtreeview1 = ScrolledTreeView(self.Frame1)
        self.Scrolledtreeview1.place(relx=0.02, rely=0.03, relheight=0.57
                , relwidth=0.92)
        self.Scrolledtreeview1.configure(columns="Col1 Col2 Col3 Col4 Col5 Col6 Col7")
        self.Scrolledtreeview1.heading("#0",text="Train")
        self.Scrolledtreeview1.heading("#0",anchor="center")
        self.Scrolledtreeview1.column("#0",width="79")
        self.Scrolledtreeview1.column("#0",minwidth="20")
        self.Scrolledtreeview1.column("#0",stretch="1")
        self.Scrolledtreeview1.column("#0",anchor="w")
        self.Scrolledtreeview1.heading("Col1",text="Time")
        self.Scrolledtreeview1.heading("Col1",anchor="center")
        self.Scrolledtreeview1.column("Col1",width="90")
        self.Scrolledtreeview1.column("Col1",minwidth="20")
        self.Scrolledtreeview1.column("Col1",stretch="1")
        self.Scrolledtreeview1.column("Col1",anchor="w")
        self.Scrolledtreeview1.heading("Col2",text="Departs")
        self.Scrolledtreeview1.heading("Col2",anchor="center")
        self.Scrolledtreeview1.column("Col2",width="106")
        self.Scrolledtreeview1.column("Col2",minwidth="20")
        self.Scrolledtreeview1.column("Col2",stretch="1")
        self.Scrolledtreeview1.column("Col2",anchor="w")
        self.Scrolledtreeview1.heading("Col3",text="Arrives")
        self.Scrolledtreeview1.heading("Col3",anchor="center")
        self.Scrolledtreeview1.column("Col3",width="106")
        self.Scrolledtreeview1.column("Col3",minwidth="20")
        self.Scrolledtreeview1.column("Col3",stretch="1")
        self.Scrolledtreeview1.column("Col3",anchor="w")
        self.Scrolledtreeview1.heading("Col4",text="class")
        self.Scrolledtreeview1.heading("Col4",anchor="center")
        self.Scrolledtreeview1.column("Col4",width="46")
        self.Scrolledtreeview1.column("Col4",minwidth="20")
        self.Scrolledtreeview1.column("Col4",stretch="1")
        self.Scrolledtreeview1.column("Col4",anchor="w")
        self.Scrolledtreeview1.heading("Col5",text="Price")
        self.Scrolledtreeview1.heading("Col5",anchor="center")
        self.Scrolledtreeview1.column("Col5",width="42")
        self.Scrolledtreeview1.column("Col5",minwidth="20")
        self.Scrolledtreeview1.column("Col5",stretch="1")
        self.Scrolledtreeview1.column("Col5",anchor="w")
        self.Scrolledtreeview1.heading("Col6",text="#bags")
        self.Scrolledtreeview1.heading("Col6",anchor="center")
        self.Scrolledtreeview1.column("Col6",width="40")
        self.Scrolledtreeview1.column("Col6",minwidth="20")
        self.Scrolledtreeview1.column("Col6",stretch="1")
        self.Scrolledtreeview1.column("Col6",anchor="w")
        self.Scrolledtreeview1.heading("Col7",text="Name")
        self.Scrolledtreeview1.heading("Col7",anchor="center")
        self.Scrolledtreeview1.column("Col7",width="69")
        self.Scrolledtreeview1.column("Col7",minwidth="20")
        self.Scrolledtreeview1.column("Col7",stretch="1")
        self.Scrolledtreeview1.column("Col7",anchor="w")

        self.Button3 = Button(self.Frame1)
        self.Button3.place(relx=0.11, rely=0.67, height=26, width=55)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(text='''Back''')

        self.Button4 = Button(self.Frame1)
        self.Button4.place(relx=0.36, rely=0.67, height=26, width=80)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(text='''Continue''')

        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.01, rely=0.18, relheight=0.7, relwidth=0.95)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(width=645)

        self.Listbox1 = Listbox(self.Frame2)
        self.Listbox1.place(relx=0.08, rely=0.16, relheight=0.2, relwidth=0.73)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(width=474)

        self.Listbox2 = Listbox(self.Frame2)
        self.Listbox2.place(relx=0.08, rely=0.51, relheight=0.2, relwidth=0.73)
        self.Listbox2.configure(background="white")
        self.Listbox2.configure(font="TkFixedFont")
        self.Listbox2.configure(width=474)

        self.Label3 = Label(self.Frame2)
        self.Label3.place(relx=0.11, rely=0.73, height=18, width=72)
        self.Label3.configure(text='''Change fee''')

        self.Label4 = Label(self.Frame2)
        self.Label4.place(relx=0.09, rely=0.83, height=18, width=86)
        self.Label4.configure(text='''Updated Cost''')

        self.Listbox3 = Listbox(self.Frame2)
        self.Listbox3.place(relx=0.25, rely=0.73, relheight=0.08, relwidth=0.13)
        self.Listbox3.configure(background="white")
        self.Listbox3.configure(font="TkFixedFont")
        self.Listbox3.configure(width=84)

        self.Listbox4 = Listbox(self.Frame2)
        self.Listbox4.place(relx=0.25, rely=0.83, relheight=0.11, relwidth=0.13)
        self.Listbox4.configure(background="white")
        self.Listbox4.configure(font="TkFixedFont")
        self.Listbox4.configure(width=84)

        self.Label5 = Label(self.Frame2)
        self.Label5.place(relx=0.08, rely=0.1, height=18, width=122)
        self.Label5.configure(text='''Current Train ticket''')

        self.Label6 = Label(self.Frame2)
        self.Label6.place(relx=0.09, rely=0.38, height=18, width=127)
        self.Label6.configure(text='''New Departure Date''')

        self.Entry2 = Entry(self.Frame2)
        self.Entry2.place(relx=0.31, rely=0.38, relheight=0.06, relwidth=0.23)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")

        self.Button5 = Button(self.Frame2)
        self.Button5.place(relx=0.51, rely=0.79, height=26, width=55)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(text='''Back''')

        self.Button6 = Button(self.Frame2)
        self.Button6.place(relx=0.67, rely=0.79, height=26, width=70)
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(text='''Submit''')





# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=self._autoscroll(vsb),
        #    xscrollcommand=self._autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = Pack.__dict__.keys() | Grid.__dict__.keys() \
                  | Place.__dict__.keys()
        else:
            methods = Pack.__dict__.keys() + Grid.__dict__.keys() \
                  + Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        return func(cls, container, **kw)
    return wrapped

class ScrolledTreeView(AutoScroll, ttk.Treeview):
    '''A standard ttk Treeview widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        ttk.Treeview.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)


if __name__ == '__main__':
    vp_start_gui()



