#############################################################################
# Generated by PAGE version 4.7
# in conjunction with Tcl version 8.6
#    Apr 24, 2016 03:11:33 AM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.scr37

    #Updating ttreeview attributes
    .top36.scr37.01 configure\
        -columns  "Col1 Col2"\
        -height  4

    #heading options.
    .top36.scr37.01 heading Col1 \
             -text "Train Number" \
             -anchor center
    #heading options.
    .top36.scr37.01 heading Col2 \
             -text "#reservations" \
             -anchor center
    #heading options.
    .top36.scr37.01 heading #0 \
             -text "Month" \
             -anchor center
    #column options.
    .top36.scr37.01 column Col1 \
             -width 132 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    #column options.
    .top36.scr37.01 column Col2 \
             -width 208 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    #column options.
    .top36.scr37.01 column #0 \
             -width 112 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 600x450+248+128
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1244 723
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "View Popular Route Report"
    vTcl:DefineAlias "$top" "popularreport" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font TkDefaultFont
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr37 \
        -background {#d9d9d9} -height 268 -highlightcolor black -width 550 
    vTcl:DefineAlias "$top.scr37" "Scrolledtreeview1" vTcl:WidgetProc "popularreport" 1
    button $top.but38 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text Close 
    vTcl:DefineAlias "$top.but38" "Button1" vTcl:WidgetProc "popularreport" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.scr37 \
        -in $top -x 30 -y 30 -width 466 -height 268 -anchor nw \
        -bordermode ignore 
    place $top.but38 \
        -in $top -x 120 -y 360 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

